### ISSUE TITLE
can you post the source for the py modules (so we can view it without opening the blend)

### ISSUE THREAD

**Issue by BluePrintRandom** [UnidayStudio/UPBGE-CharacterController#1]
There are security issues on upbge versions before  recent commits 0.2.3

(py components run automatically without any asking for permission)

so it's a good idea to let the user build components with copy/paste into their own projects
and allow them to look over the code without opening a blend in upbge.

**Comment by UnidayStudio** [comment]
But the sources are already available outside the blend file:
https://github.com/UnidayStudio/UPBGE-CharacterController/tree/master/Source

**Comment by BluePrintRandom** [comment]
I am silly - but can we save the source also in the blend? (text editor?)

**Comment by UnidayStudio** [comment]
I don't see a problem with this. So you can. Just remember to add me on the credits of the project. :)
