### ISSUE TITLE
Use SCA_InputEvent.active instead of SCA_InputEvent.values

### ISSUE THREAD

**Issue by panzergame** [UnidayStudio/UPBGE-CharacterController#2]
https://github.com/UnidayStudio/UPBGE-CharacterController/blob/c039b17e94c09ac10e2e8f78ae02b9073d14a5c4/Source/CharacterController.py#L75
https://github.com/UnidayStudio/UPBGE-CharacterController/blob/c039b17e94c09ac10e2e8f78ae02b9073d14a5c4/Source/CharacterController.py#L123

`SCA_InputEvent.values` exists for keyboard events only because the mouse events need this field to store the mouse position or wheel rotation.

Also using the last item of `values` mean that item in the between are ignored, if the key is pressed and released and that a frame contain only these two actions, the last value will be 0 and you will miss the activation.

You should use the helpers: 
https://pythonapi.upbge.org/bge.types.SCA_InputEvent.html#bge.types.SCA_InputEvent.active
https://pythonapi.upbge.org/bge.types.SCA_InputEvent.html#bge.types.SCA_InputEvent.inactive
https://pythonapi.upbge.org/bge.types.SCA_InputEvent.html#bge.types.SCA_InputEvent.activated
https://pythonapi.upbge.org/bge.types.SCA_InputEvent.html#bge.types.SCA_InputEvent.deactivated

```python
if keyboard[bge.events.LEFTSHIFTKEY].values[-1]:
    speed = self.runSpeed
```

```python
if keyboard[bge.events.LEFTSHIFTKEY].active:
    speed = self.runSpeed
```

**Comment by UnidayStudio** [comment]
Fine! Fixed here:
https://github.com/UnidayStudio/UPBGE-CharacterController/commit/e923e9f8ad3cb90cf3e2c2e62ab9a6b5f3abe89b
