### ISSUE TITLE
mathutils normalize

### ISSUE THREAD

**Issue by panzergame** [UnidayStudio/UPBGE-CharacterController#3]
https://github.com/UnidayStudio/UPBGE-CharacterController/blob/c039b17e94c09ac10e2e8f78ae02b9073d14a5c4/Source/CharacterController.py#L87

What do you mean in this comment ? Should we leave it in the code ?

**Comment by paul-marechal** [comment]
```py
from mathutils import Vector

# vectors with size == 10
v1 = Vector((0, 0, 10))
v2 = Vector((0, 0, 10))

returnValue = v1.normalize()
# v1 == Vector((0, 0, 1))
# returnValue is None

normalised = v2.normalised()
# normalised == Vector((0, 0, 1))
# v2 == Vector((0, 0, 10))
```

Be careful when using one of both functions:
- https://docs.blender.org/api/2.79/mathutils.html#mathutils.Vector.normalize
- https://docs.blender.org/api/2.79/mathutils.html#mathutils.Vector.normalized

**Comment by UnidayStudio** [comment]
Oh, I didn't knew this. I'll fix and remove the comment.

**Comment by UnidayStudio** [comment]
Fixed:
https://github.com/UnidayStudio/UPBGE-CharacterController/commit/e923e9f8ad3cb90cf3e2c2e62ab9a6b5f3abe89b

Thanks to @marechal-p I discovered that there is no problems with mathutils normalization, I just didn't new which one to use. My Bad.
