### ISSUE TITLE
Use vector.xy 

### ISSUE THREAD

**Issue by panzergame** [UnidayStudio/UPBGE-CharacterController#4]
https://github.com/UnidayStudio/UPBGE-CharacterController/blob/c039b17e94c09ac10e2e8f78ae02b9073d14a5c4/Source/CharacterController.py#L129

These lines could be replaced by:
```python
dst.xy = src.xy
``

**Comment by UnidayStudio** [comment]
Fixed:
https://github.com/UnidayStudio/UPBGE-CharacterController/commit/e923e9f8ad3cb90cf3e2c2e62ab9a6b5f3abe89b
